etcd:
  root-cert-path: /root/k8s/tmp/ca.pem
  client-cert-path: /root/k8s/tmp/server.pem
  client-key-cert-path: /root/k8s/tmp/server-key.pem
  endpoints: [https://172.16.200.167:2379,https://172.16.200.168:2379,https://172.16.200.169:2379]

server:
  host: http://172.16.200.167:9067
  apis:
    run: /v1/server/run
    stop: /v1/server/stop
    healthy: /v1/server/healthy
    list: /v1/server/list
  ipRange: 172.244.0.0/24
  repo: http://172.16.200.116:8081/repository/appManager/
  polling: [1,2,3,5,8,13,21,34,55,89,144]